image:
  file: .gitpod.dockerfile

ports:
  - port: 8000
    onOpen: ignore
  - port: 3306
    onOpen: ignore
    
tasks:
  - init: composer install
    #command: mysql create database evote
    #command: mysql create user evote password evote
    #command: mysql GRANT ALL PRIVILEGES ON evote TO 'evote'@'localhost';
  - name: MySQL
    command: >
        mysqld

