image:
  file: .gitpod.dockerfile

ports:
  - port: 8000
    onOpen: ignore
  - port: 3306
    onOpen: ignore
    
tasks:
  - init: composer install
  - name: MySQL
    command: >
        mysqld
  - command: mysql -e "alter user 'root'@'localhost' identified with mysql_native_password by 'Pass$$'"
  - command: php src/db/resetDatabase.php
  - command: composer serve

